USE jotd;

-- Drop tables

DROP TABLE IF EXISTS Joke;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS AuthenticatedUser;

-- Create tables

CREATE TABLE Joke (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  joke  TEXT NOT NULL,
  added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE User (
  id       BIGINT    AUTO_INCREMENT PRIMARY KEY,
  email    VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255)        NOT NULL,
  created  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AuthenticatedUser (
  id      BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT              NOT NULL,
  token   VARCHAR(255) UNIQUE NOT NULL,

  FOREIGN KEY (user_id)
  REFERENCES User (id)
    ON DELETE RESTRICT
);